project:
  type: website
  output-dir: docs
  execute-dir: file

website:
  title: "Ontario eFRI"
  navbar:
    left:
      - href: index.qmd
        text: "Introduction"
      - href: data_and_method.qmd
        text: "Data and Methods"
      - href: project_outputs.qmd
        text: "Project Outputs"
      - href: segmentation_parameters_optimisation.qmd
        text: "Appendix A : Segmentation parameters optimisation"

format:
  html:
    theme: cosmo
    toc: true
    crossref:
      fig-title: "Figure"
      fig-prefix: "Figure"
      tbl-title: "Table"
      tbl-prefix: "Table"
      title-delim: "."
