project:
  type: website
  output-dir: docs
  execute-dir: file

website:
  title: "Ontario eFRI"
  navbar:
    left:
      - href: index.qmd
        text: "Introduction"
      - href: data_and_method.qmd
        text: "Data and Methods"
      # - href: projet_ouputs.qmd
      #   text: Project Outputs
      - href: calibration_grm.qmd
        text: "Appendix A : Segmentation paramaters optimisation"

format:
  html:
    theme: cosmo
    toc: true
